name = "chatgpt_discord_api"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-05-13"
logpush = true
send_metrics = true

kv_namespaces = [
  { binding = "ChatGPT_Thread", id = "3953fc8f715543c49107d62cf6e11df1", preview_id = "fe834d85a6164c0eb815a7dfe0fb19fa" },
]
